In [25]:
import os
import pandas as pd

['po-obcinah_izobrazba.csv',
 'po-obcinah_spol.csv',
 'po-obcinah_starost.csv',
 'po-obcinah_trajanje-brezposelnosti.csv',
 'po-statisticnah-regijah_izobrazba.csv',
 'po-statisticnah-regijah_spol.csv',
 'po-statisticnah-regijah_starost.csv',
 'po-statisticnah-regijah_trajanje-brezposelnosti.csv',
 'po-uradih-za-delo_izobrazba.csv',
 'po-uradih-za-delo_spol.csv',
 'po-uradih-za-delo_starost.csv',
 'po-uradih-za-delo_trajanje-brezposelnosti.csv',
 'zaposleni',
 'zaposleni_po_obcinah.csv',
 'zaposleni_po_regijah.csv']

In [28]:
df = pd.read_excel('../structured_data/zaposleni/zaposleni_po_regijah.xlsx', header=[0, 1])

In [29]:
df

,Unnamed: 0,15-24,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 1413,Unnamed: 1414,Unnamed: 1415,Unnamed: 1416,Unnamed: 1417,Unnamed: 1418,Unnamed: 1419,Unnamed: 1420,Unnamed: 1421,Unnamed: 1422
0,NaN,2010M01,2010M02,2010M03,2010M04,2010M05,2010M06,2010M07,2010M08,2010M09,...,2022M05,2022M06,2022M07,2022M08,2022M09,2022M10,2022M11,2022M12,2023M01,2023M02
1,SLOVENIA,38654,38277,37915,37485,36886,36609,35836,35185,35592,...,55673,56451,56830,57502,57618,58328,58982,59845,57739,58017
2,Pomurska,1915,1926,1930,1965,1962,1983,1973,1939,1891,...,2970,3010,3022,3041,3069,3110,3145,3177,3035,3052
3,Podravska,5366,5332,5326,5244,5125,5076,5014,4956,5003,...,8603,8761,8893,8988,8971,9070,9153,9396,8944,8997
4,Koro≈°ka,1390,1362,1342,1326,1303,1309,1277,1258,1263,...,1807,1821,1854,1886,1892,1918,1943,1980,1892,1889
5,Savinjska,5059,4964,4884,4852,4824,4797,4671,4617,4703,...,6225,6310,6344,6442,6434,6513,6579,6661,6435,6472
6,Zasavska,928,939,940,925,908,905,889,875,894,...,1334,1354,1370,1384,1386,1423,1442,1467,1389,1393
7,Posavska,1572,1542,1544,1529,1510,1502,1455,1413,1444,...,1905,1915,1947,1963,1955,1972,1993,2017,1962,1976
8,Jugovzhodna Slovenija,3170,3145,3132,3111,3058,3058,2959,2861,2931,...,3504,3575,3580,3624,3641,3683,3747,3812,3623,3654
9,Osrednjeslovenska,9639,9528,9338,9195,9044,8934,8712,8543,8623,...,15573,15760,15811,15989,16029,16228,16459,16696,16363,16425
10,Gorenjska,4127,4124,4055,3987,3900,3878,3811,3762,3797,...,5015,5098,5131,5183,5198,5266,5321,5349,5121,5139
11,Primorsko-notranjska,1238,1249,1234,1207,1172,1154,1149,1121,1114,...,1527,1542,1527,1542,1556,1565,1574,1596,1515,1518
12,Gori≈°ka,2061,2016,2007,1985,1941,1901,1854,1809,1881,...,3196,3241,3274,3322,3321,3372,3396,3428,3318,3342
13,Obalno-kra≈°ka,2189,2150,2183,2159,2139,2112,2072,2031,2048,...,4014,4064,4077,4138,4166,4208,4230,4266,4142,4160